version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - '3333:3333'
    depends_on:
      - db
    networks:
      - project-network

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - project-network

  front:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    container_name: front
    ports:
      - '5173:5173'
    env_file:
      - ./Frontend/.env
    networks:
      - project-network
  game:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: game
    ports:
      - '2567:2567'
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
